env:
    CONFIG: env.conf
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    CIRRUS_SHELL: bash
    rlslone_config: "ENCRYPTED[!e8b279088dcc3b09fe2fef9f6fa8e063fdc69cdd1dc93e7356b67768ca5be66c24f63ff9f06dc22e64edb1d68527b819!]"
    GIT_TOKEN: "ENCRYPTED[!1877e8636cbcf281ffd947efb492bd083f8c0f6efebbd62a6eb386961499bcd9886d6e16f2052725cedc9987ff821058!]"
    TG_TOKEN: "ENCRYPTED[!ceca6b4c483b6931cd0e197a5c95d2e59c7044c3256c7d302f19f9445fbf643184716625a91792ba0b8c7398c66dd7d6!]"
    CCACHE_INDEX_DOWNLOAD_URL: "ENCRYPTED[!c7d1eb8415f7de20d85790ee59eb56b3ff415d378576420971a5cc5607035de092bcba28df4139fe0e4b5c778a6cfccc!]"
    GIT_COOKIES_RAW_GIST: "ENCRYPTED[!c7219504638882e56d929be0daf830f94eb2df19f6c26667efef1f25b1c463bd25690bc61eb3d1dda991e3f9d154450d!]"
    
task:
    name: Build
    timeout_in: 2h
    container:
      image: madhavsheth/android_build_environment:latest
      cpu: 8
      memory: 32g
      greedy: true
    
    setupcc_script:
      - bash privatize_repo.sh
      - if [[ "$(tail -1 download_ccache.sh)" -ge "15" ]]; then echo "Build Failed!" && exit 1; fi
      - if [[ "$(tail -1 download_ccache.sh)" == "CCACHE_RUN=0" ]]; then echo 'skip ccache'; else bash download_ccache.sh ; fi
    additional_script:
      - bash additional.sh || true
    sync_script:
      - if ! timeout 15m bash sync.sh; then bash publisize_repo.sh && bash retry_sync.sh && sleep 5s; fi
    patch_script:
      - bash patch.sh
    build_script:
      - bash build.sh      
    ccupload_script:
      - bash upload_ccache.sh
    telegram_script:
      - bash tg.sh || true
      - sleep 10s
